a = input('Digíte algo: ')
print('O tipo primitívo desse valor é',type(a))
print('Só tem espaços?',a.isspace())
print('É um número?',a.isnumeric())
print('É alfabético?',a.isalpha())
print('É alfanumérico?',a.isalnum())
print('Está em letras maiúsculas?',a.isupper())
print('está em minúsculas?',a.islower())
print('Está capitalizada?',a.istitle())
